# Generated by Django 5.2.14 on 2026-07-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
